# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31c403cadf4d2516d2447bf5414d70a14aa75212d6c8d36f8e3b0aa7035f64a42e7cac7cd07a5363ea8b8aa079ff165311d760d65bbf6b8d328d13b3a4b19242

test:
  secret_key_base: 7243ff644151699c490a0c483069e0b9340d682d5860e4e512323eee01334d4205a06d93431fecbbb24092a47df24e6e86f785269646e3d2d4541a831d88e8fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
